{% set name = "obplatform" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f82ae8f7f41368f392ccfdd00c8464ca55815e5b9d6d36d13a3888d850a4714

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
  run:
    - python >=3.7.1,<4.0
    - requests >=2
    - tqdm >=4

test:
  imports:
    - obplatform
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/umonaca/obplatform
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'APIs to access ASHRAE OB Database'
  description: |
    A package to interact and download behavior data from ASHRAE Global Occupant Behavior Database.
  doc_url: https://obplatform.readthedocs.io/
  dev_url: https://github.com/umonaca/obplatform/

extra:
  recipe-maintainers:
    - umonaca
